sudo: required
language: python

# which python versions to test
python:
  - "2.7"
  - "3.4"
#  - "3.5"
#  - "3.6"
#  - "3.5-dev" # 3.5 development branch
#  - "3.6"
#  - "3.6-dev" # 3.6 development branch
#  - "3.7-dev" # 3.7 development branch
#  - "nightly"
#

matrix:
  allow_failures:
    - python: "2.7"
    - python: "3.4"
#    - python: "3.5"
#    - python: "3.6"

virtualenv:
    system_site_packages: true

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .

# command to run tests
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 || $TRAVIS_PYTHON_VERSION == 3.5 ]]; then py.test tests/expressions ;else pytest tests/expressions; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 || $TRAVIS_PYTHON_VERSION == 3.5 ]]; then py.test tests/glt ;else pytest tests/glt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 || $TRAVIS_PYTHON_VERSION == 3.5 ]]; then py.test tests/weak_form ;else pytest tests/weak_form; fi
